/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_57095a78 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/plzsvzwwcdopnawtiwzm/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_57095a78").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_57095a78").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_57095a78").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
/**
 * Sets multiple key-value pairs.
 *
 * Accepts either calling convention, because both are in use and only one of
 * them ever worked:
 *
 *   mset(["a", "b"], [1, 2])                    two parallel arrays
 *   mset([{ key: "a", value: 1 }, …])           a single array of pairs
 *
 * Four callers used the second form against a signature that only understood
 * the first — investments-kv's opportunity seeder among them, which is why the
 * investor portal has never had a single opportunity in it. The keys array held
 * objects and the values array was undefined, so every row upserted a
 * stringified object against an undefined value, or failed outright.
 *
 * Supporting both is a smaller and safer change than editing five call sites,
 * and it removes the trap rather than fixing one instance of it.
 */
export const mset = async (
  keysOrPairs: string[] | Array<{ key: string; value: any }>,
  values?: any[],
): Promise<void> => {
  const supabase = client()
  const rows = Array.isArray(values)
    ? (keysOrPairs as string[]).map((k, i) => ({ key: String(k), value: values[i] }))
    : (keysOrPairs as Array<{ key: string; value: any }>).map((p) => ({ key: String(p?.key), value: p?.value }));

  if (!rows.length) return;
  const bad = rows.find((r) => !r.key || r.key === "undefined" || r.key === "[object Object]");
  if (bad) throw new Error(`mset was given an unusable key: ${JSON.stringify(bad.key)}`);

  const { error } = await supabase.from("kv_store_57095a78").upsert(rows);
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_57095a78").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_57095a78").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_57095a78").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};