/**
 * quotes — server routes backing the Invoice/Estimate builder (InvoiceBuilder.tsx).
 *
 * Quotes (estimates) and invoices are persisted here so they survive refreshes
 * and sync across devices. A quote can be created WITHOUT a customer and be
 * assigned (or reassigned) to one later via the /assign route.
 *
 * KV keys: `quote:{id}`
 */

import { Hono } from "npm:hono";
import { cors } from "npm:hono/cors";
import { createClient } from "npm:@supabase/supabase-js@2";
import * as kv from "./kv_store.tsx";

const quotesRouter = new Hono();

// ─────────────────────────────────────────────────────────────────────────────
// WHO IS ASKING
//
// A customer approves their own quote from the portal, so this cannot be
// staff-only. It also cannot be open: listing every quote returned every
// customer's pricing, line items and contact details to anyone who asked.
//
// Staff see everything; a customer sees the quotes addressed to them. A quote
// with no client email yet — they can be created before being assigned — is
// visible to staff only, because there is nobody it can be proven to belong to.
// ─────────────────────────────────────────────────────────────────────────────

const STAFF_ROLES = new Set(['owner', 'platform_owner', 'business_owner', 'admin', 'master_admin', 'management']);

function service() {
  return createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );
}

async function quoteActor(c: any): Promise<{ email: string; staff: boolean }> {
  const token = String(c.req.header("Authorization") || "").replace(/^Bearer\s+/i, "");
  if (!token) return { email: "", staff: false };
  const { data, error } = await service().auth.getUser(token);
  const user = error ? null : data?.user;
  if (!user?.email) return { email: "", staff: false };

  const owners = (Deno.env.get("PLATFORM_OWNER_EMAILS") || "")
    .split(",").map((s) => s.trim().toLowerCase()).filter(Boolean);
  const email = String(user.email).toLowerCase();
  const role = String(
    user.app_metadata?.role || user.app_metadata?.accountType || "",
  ).toLowerCase().replace(/[\s-]+/g, "_");

  return { email, staff: owners.includes(email) || STAFF_ROLES.has(role) };
}

// ─────────────────────────────────────────────────────────────────────────────
// QUOTE NUMBERS
//
// These used to be minted in the browser: `QT-<date>-<four random digits>`, in
// two different places in the pipeline, with the invoice builder running a third
// scheme of its own. Random numbers can collide — four digits inside one day is
// 9,999 of them — and a sequence nobody can count is a sequence that cannot be
// audited. Every quote in the store still carries one of those.
//
// They are minted here now, once, when a quote is first created. Eric's call:
// numbered on creation rather than on approval, so every quote has a number
// while it is being discussed, and gaps in the run are quotes that went nowhere.
//
// HOW IT STAYS UNIQUE WITHOUT A SCHEMA CHANGE
//
// The number is claimed by inserting a row whose key IS the number. The kv table
// has `key` as its primary key, so a second claim on the same number fails at
// the database rather than racing in application code. The counter beside it is
// only a hint about where to start looking, so losing it costs a few wasted
// attempts and never a duplicate.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Must match the table in kv_store.tsx, which is marked autogenerated and is not
 * to be hand-edited — so this is stated here rather than exported from there.
 */
const KV_TABLE = "kv_store_57095a78";

/** Reserve a number. False when someone else already holds it. */
async function claimNumber(number: string): Promise<boolean> {
  const { error } = await service().from(KV_TABLE).insert({
    key: `quote_number:${number}`,
    value: { number, claimedAt: new Date().toISOString() },
  });
  if (!error) return true;
  // 23505 is Postgres' unique_violation: the number is taken, try the next.
  if (String((error as any).code) === "23505") return false;
  throw new Error(error.message);
}

/** The next free quote number for this year, e.g. Q-2026-0007. */
async function mintQuoteNumber(): Promise<string> {
  const year = new Date().getFullYear();
  const seqKey = `quote_seq:${year}`;
  let n = Number(await kv.get(seqKey)) || 0;

  // Bounded: a run of taken numbers means the counter is behind, not that the
  // year is full. Fifty attempts recovers from that without spinning forever.
  for (let attempt = 0; attempt < 50; attempt++) {
    n += 1;
    const number = `Q-${year}-${String(n).padStart(4, "0")}`;
    if (await claimNumber(number)) {
      await kv.set(seqKey, n);
      return number;
    }
  }
  throw new Error("Could not allocate a quote number after 50 attempts.");
}

/** True when this quote is addressed to that email. */
function quoteBelongsTo(doc: any, email: string): boolean {
  const target = String(email || "").trim().toLowerCase();
  if (!target) return false;
  return [doc?.clientEmail, doc?.client_email, doc?.customerEmail, doc?.email]
    .some((value: any) => String(value || "").trim().toLowerCase() === target);
}

quotesRouter.use("*", cors({
  origin: "*",
  allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
  allowHeaders: ["Content-Type", "Authorization"],
  exposeHeaders: ["Content-Length"],
  maxAge: 600,
  credentials: false,
}));

// Normalize a quote/invoice document into a consistent stored shape.
function normalizeDoc(input: any) {
  return {
    id: String(input.id || `Q-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`),
    type: input.type === "invoice" ? "invoice" : "estimate",
    number: String(input.number || ""),
    // Embedded client fields (may be empty — an unassigned quote).
    clientName: String(input.clientName || ""),
    clientEmail: String(input.clientEmail || ""),
    clientPhone: String(input.clientPhone || ""),
    clientAddress: String(input.clientAddress || ""),
    // Real link to a CRM customer, if one has been assigned.
    customerId: input.customerId ? String(input.customerId) : "",
    issueDate: String(input.issueDate || ""),
    dueDate: String(input.dueDate || ""),
    items: Array.isArray(input.items) ? input.items : [],
    // Subcontractor quotes folded into this quote — kept on OUR side (internal record).
    subQuotes: Array.isArray(input.subQuotes) ? input.subQuotes : [],
    // Design Studio round-trip: floor plan + design-extracted materials.
    floorPlanData: input.floorPlanData ?? null,
    designMaterials: Array.isArray(input.designMaterials) ? input.designMaterials : [],
    // Buildable plans & renderings (stored in Storage; metadata only here).
    deliverables: Array.isArray(input.deliverables) ? input.deliverables : [],
    notes: String(input.notes || ""),
    taxRate: Number(input.taxRate) || 0,
    /**
     * Where this quote came from.
     *
     * The pipeline has always sent `workRequestId` when it saves a quote, and
     * this function has always dropped it, because it rebuilds the record field
     * by field and that field was never listed. So "this quote came from that
     * request" was recorded nowhere, and every quote in the store has an empty
     * one. Keeping it costs a line.
     */
    workRequestId: input.workRequestId ? String(input.workRequestId) : "",
    /** Also sent by the pipeline and also silently discarded until now. */
    total: Number(input.total) || 0,
    /**
     * `approved` and `rejected` are the customer's decision, written by the
     * public signing route in index.tsx. They were missing from this list, so
     * the first save after an approval — a pipeline update, an edit in the
     * invoice builder — rewrote the quote as a draft and the approval vanished
     * with no error. A customer's signature is not something to lose quietly.
     */
    status: ["draft", "sent", "viewed", "approved", "rejected", "paid"].includes(input.status)
      ? input.status : "draft",
    /** The signature that goes with an approval, preserved for the same reason. */
    signature: input.signature ?? null,
    createdAt: String(input.createdAt || new Date().toISOString()),
    updatedAt: new Date().toISOString(),
  };
}


/**
 * Only the company writes a quote.
 *
 * `quoteActor` already existed here and the list route uses it properly —
 * staff see every quote, a customer sees only their own. The four write
 * handlers used it nowhere, so any signed-in account could create, edit,
 * reassign or delete any quote by id. A quote becomes a contract and then an
 * invoice, so that is the price of a job editable by whoever asks.
 *
 * The customer portal only ever lists quotes; nothing outside the company
 * writes one.
 */
async function requireQuoteStaff(c: any): Promise<Response | null> {
  const { email, staff } = await quoteActor(c);
  if (!email) return c.json({ success: false, error: "Sign in required." }, 401);
  if (!staff) return c.json({ success: false, error: "Administrator access is required." }, 403);
  return null;
}

// ── List all quotes/invoices ──────────────────────────────────────────────────
quotesRouter.get("/make-server-3eae23a6/quotes", async (c) => {
  try {
    const { email, staff } = await quoteActor(c);
    if (!email) return c.json({ success: false, error: "Sign in required." }, 401);
    const docs = (await kv.getByPrefix("quote:")) || [];
    return c.json({ success: true, quotes: staff ? docs : docs.filter((doc: any) => quoteBelongsTo(doc, email)) });
  } catch (error) {
    console.error("[Quotes] Error fetching quotes:", error);
    return c.json({ success: false, error: "Failed to load quotes", details: String(error) }, 500);
  }
});

// ── Create or update a quote/invoice ──────────────────────────────────────────
quotesRouter.post("/make-server-3eae23a6/quotes", async (c) => {
  const refused = await requireQuoteStaff(c);
  if (refused) return refused;

  try {
    const body = await c.req.json();
    const input = body?.quote || body;
    if (!input || typeof input !== "object") {
      return c.json({ success: false, error: "`quote` payload is required" }, 400);
    }
    const existing = input.id ? await kv.get(`quote:${input.id}`) : null;

    // A number is minted once, on creation, and never reissued. An existing
    // quote keeps the number it was given even if a caller sends a different
    // one — a number that changes under a customer is worse than no number,
    // because they have it written down.
    const carried = String((existing as any)?.number || "").trim();
    const number = carried || await mintQuoteNumber();

    const doc = normalizeDoc({ ...(existing || {}), ...input, number });
    await kv.set(`quote:${doc.id}`, doc);
    console.log(`[Quotes] Saved ${doc.type} ${doc.number} (${doc.id})${doc.customerId ? " → customer " + doc.customerId : " (unassigned)"}`);
    return c.json({ success: true, quote: doc });
  } catch (error) {
    console.error("[Quotes] Error saving quote:", error);
    return c.json({ success: false, error: "Failed to save quote", details: String(error) }, 500);
  }
});

// ── Partial update (used by Design Studio to save the floor plan back) ─────────
// Design Studio sends { floorPlanData, materials, lastModified } — we merge those
// onto the existing quote without clobbering the customer-facing line items.
quotesRouter.put("/make-server-3eae23a6/quotes/:id", async (c) => {
  const refused = await requireQuoteStaff(c);
  if (refused) return refused;

  try {
    const id = c.req.param("id");
    const body = await c.req.json();
    const existing = await kv.get(`quote:${id}`);
    if (!existing) {
      return c.json({ success: false, error: `Quote ${id} not found` }, 404);
    }
    const merged = {
      ...existing,
      // Design Studio's "materials" are the design-extracted list — store them
      // separately as designMaterials so manual line items stay intact.
      designMaterials: Array.isArray(body.materials) ? body.materials
        : (Array.isArray(body.designMaterials) ? body.designMaterials : existing.designMaterials),
      floorPlanData: body.floorPlanData ?? existing.floorPlanData ?? null,
    };
    const doc = normalizeDoc(merged);
    await kv.set(`quote:${id}`, doc);
    console.log(`[Quotes] Updated quote ${id} from Design Studio (${doc.designMaterials.length} design materials)`);
    return c.json({ success: true, quote: doc });
  } catch (error) {
    console.error("[Quotes] Error updating quote:", error);
    return c.json({ success: false, error: "Failed to update quote", details: String(error) }, 500);
  }
});

// ── Assign / reassign a customer to an existing quote ─────────────────────────
quotesRouter.post("/make-server-3eae23a6/quotes/:id/assign", async (c) => {
  const refused = await requireQuoteStaff(c);
  if (refused) return refused;

  try {
    const id = c.req.param("id");
    const body = await c.req.json();
    const existing = await kv.get(`quote:${id}`);
    if (!existing) {
      return c.json({ success: false, error: `Quote ${id} not found` }, 404);
    }
    const doc = normalizeDoc({
      ...existing,
      customerId: body.customerId || "",
      clientName: body.clientName ?? existing.clientName,
      clientEmail: body.clientEmail ?? existing.clientEmail,
      clientPhone: body.clientPhone ?? existing.clientPhone,
      clientAddress: body.clientAddress ?? existing.clientAddress,
    });
    await kv.set(`quote:${id}`, doc);
    console.log(`[Quotes] Assigned quote ${id} to customer ${doc.customerId || "(cleared)"}`);
    return c.json({ success: true, quote: doc });
  } catch (error) {
    console.error("[Quotes] Error assigning customer:", error);
    return c.json({ success: false, error: "Failed to assign customer", details: String(error) }, 500);
  }
});

// ── Delete a quote ────────────────────────────────────────────────────────────
quotesRouter.delete("/make-server-3eae23a6/quotes/:id", async (c) => {
  const refused = await requireQuoteStaff(c);
  if (refused) return refused;

  try {
    const id = c.req.param("id");
    await kv.del(`quote:${id}`);
    console.log(`[Quotes] Deleted quote ${id}`);
    return c.json({ success: true });
  } catch (error) {
    console.error("[Quotes] Error deleting quote:", error);
    return c.json({ success: false, error: "Failed to delete quote", details: String(error) }, 500);
  }
});

export default quotesRouter;
