// Comprehensive materials list - every consumable item needed for construction jobs
// Each item has a visibility flag to control whether it appears in customer quotes

export const getFasteners = () => [
  { name: '#10 x 2-1/2" Cabinet Installation Screws', quantity: 200, unit: 'each', unitCost: 0.18, category: 'Fasteners', visible: false },
  { name: '#8 x 1-1/4" Cabinet Hardware Screws', quantity: 100, unit: 'each', unitCost: 0.12, category: 'Fasteners', visible: false },
  { name: '2-1/2" Brad Nails (18 gauge)', quantity: 1000, unit: 'each', unitCost: 0.05, category: 'Fasteners', visible: false },
  { name: '1-1/4" Brad Nails (18 gauge)', quantity: 500, unit: 'each', unitCost: 0.04, category: 'Fasteners', visible: false },
  { name: '2" Finish Nails (16 gauge)', quantity: 500, unit: 'each', unitCost: 0.06, category: 'Fasteners', visible: false },
  { name: '3" Framing Nails', quantity: 300, unit: 'each', unitCost: 0.08, category: 'Fasteners', visible: false },
  { name: '1-5/8" Drywall Screws', quantity: 500, unit: 'each', unitCost: 0.03, category: 'Fasteners', visible: false },
  { name: '2-1/2" Drywall Screws', quantity: 300, unit: 'each', unitCost: 0.04, category: 'Fasteners', visible: false },
  { name: '1/4" x 3" Lag Bolts', quantity: 50, unit: 'each', unitCost: 0.45, category: 'Fasteners', visible: false },
  { name: '3/8" x 4" Lag Bolts', quantity: 40, unit: 'each', unitCost: 0.65, category: 'Fasteners', visible: false },
  { name: '1/4" Flat Washers', quantity: 100, unit: 'each', unitCost: 0.08, category: 'Fasteners', visible: false },
  { name: '3/8" Flat Washers', quantity: 80, unit: 'each', unitCost: 0.12, category: 'Fasteners', visible: false },
  { name: 'Toggle Bolts 1/4" x 3"', quantity: 20, unit: 'each', unitCost: 0.85, category: 'Fasteners', visible: false },
  { name: 'Plastic Anchors #8', quantity: 100, unit: 'each', unitCost: 0.15, category: 'Fasteners', visible: false },
  { name: 'Metal Anchors #10', quantity: 50, unit: 'each', unitCost: 0.25, category: 'Fasteners', visible: false },
];

export const getAdhesivesAndSealants = () => [
  { name: 'Construction Adhesive (10.5 oz tubes)', quantity: 12, unit: 'tube', unitCost: 4.25, category: 'Adhesives & Sealants', visible: false },
  { name: 'PL Premium Polyurethane Adhesive', quantity: 8, unit: 'tube', unitCost: 6.50, category: 'Adhesives & Sealants', visible: false },
  { name: 'Wood Glue (16 oz)', quantity: 4, unit: 'bottle', unitCost: 8.95, category: 'Adhesives & Sealants', visible: false },
  { name: 'Contact Cement (1 quart)', quantity: 2, unit: 'quart', unitCost: 18.50, category: 'Adhesives & Sealants', visible: false },
  { name: 'Clear Silicone Caulk', quantity: 6, unit: 'tube', unitCost: 5.75, category: 'Adhesives & Sealants', visible: false },
  { name: 'White Acrylic Caulk (Paintable)', quantity: 8, unit: 'tube', unitCost: 3.25, category: 'Adhesives & Sealants', visible: false },
  { name: 'Kitchen & Bath Caulk (Mold Resistant)', quantity: 6, unit: 'tube', unitCost: 6.95, category: 'Adhesives & Sealants', visible: false },
  { name: 'Color-Matched Caulk', quantity: 4, unit: 'tube', unitCost: 8.50, category: 'Adhesives & Sealants', visible: false },
  { name: 'Spray Adhesive (Heavy Duty)', quantity: 4, unit: 'can', unitCost: 12.50, category: 'Adhesives & Sealants', visible: false },
  { name: 'Epoxy Two-Part Adhesive', quantity: 3, unit: 'kit', unitCost: 14.95, category: 'Adhesives & Sealants', visible: false },
  { name: 'Expanding Foam Sealant', quantity: 4, unit: 'can', unitCost: 7.25, category: 'Adhesives & Sealants', visible: false },
  { name: 'Weatherstripping Adhesive', quantity: 2, unit: 'tube', unitCost: 5.50, category: 'Adhesives & Sealants', visible: false },
];

export const getPaintSupplies = () => [
  { name: 'Interior White Primer (1 gallon)', quantity: 3, unit: 'gallon', unitCost: 24.95, category: 'Paint & Finishes', visible: false },
  { name: 'Stain-Blocking Primer (1 gallon)', quantity: 2, unit: 'gallon', unitCost: 32.50, category: 'Paint & Finishes', visible: false },
  { name: 'Semi-Gloss White Paint (1 gallon)', quantity: 4, unit: 'gallon', unitCost: 36.95, category: 'Paint & Finishes', visible: false },
  { name: 'Eggshell White Paint (1 gallon)', quantity: 3, unit: 'gallon', unitCost: 34.95, category: 'Paint & Finishes', visible: false },
  { name: 'Cabinet Paint (Urethane-Alkyd)', quantity: 2, unit: 'quart', unitCost: 28.50, category: 'Paint & Finishes', visible: false },
  { name: 'Wood Stain (1 quart)', quantity: 2, unit: 'quart', unitCost: 18.95, category: 'Paint & Finishes', visible: false },
  { name: 'Polyurethane Clear Coat (1 quart)', quantity: 2, unit: 'quart', unitCost: 22.50, category: 'Paint & Finishes', visible: false },
  { name: 'Touch-Up Paint Pens', quantity: 6, unit: 'each', unitCost: 4.25, category: 'Paint & Finishes', visible: false },
  { name: '2" Angled Paint Brush', quantity: 4, unit: 'each', unitCost: 8.95, category: 'Paint Tools', visible: false },
  { name: '3" Flat Paint Brush', quantity: 3, unit: 'each', unitCost: 12.50, category: 'Paint Tools', visible: false },
  { name: '1" Detail Brush', quantity: 3, unit: 'each', unitCost: 5.75, category: 'Paint Tools', visible: false },
  { name: '4" Mini Roller with Frame', quantity: 4, unit: 'each', unitCost: 6.25, category: 'Paint Tools', visible: false },
  { name: '9" Roller with Frame', quantity: 3, unit: 'each', unitCost: 9.95, category: 'Paint Tools', visible: false },
  { name: 'Roller Covers 3/8" Nap (pack of 6)', quantity: 2, unit: 'pack', unitCost: 14.50, category: 'Paint Tools', visible: false },
  { name: 'Roller Covers 1/2" Nap (pack of 6)', quantity: 2, unit: 'pack', unitCost: 15.95, category: 'Paint Tools', visible: false },
  { name: 'Paint Tray Liners (disposable, 10-pack)', quantity: 2, unit: 'pack', unitCost: 8.50, category: 'Paint Tools', visible: false },
  { name: 'Foam Brushes (assorted sizes, 12-pack)', quantity: 2, unit: 'pack', unitCost: 6.95, category: 'Paint Tools', visible: false },
  { name: 'Sandpaper Assortment (80-220 grit)', quantity: 3, unit: 'pack', unitCost: 12.50, category: 'Paint Tools', visible: false },
  { name: 'Sanding Sponges (Medium/Fine)', quantity: 12, unit: 'each', unitCost: 2.25, category: 'Paint Tools', visible: false },
  { name: 'Tack Cloth (12-pack)', quantity: 1, unit: 'pack', unitCost: 9.95, category: 'Paint Tools', visible: false },
  { name: 'Paint Strainer Bags (5-pack)', quantity: 1, unit: 'pack', unitCost: 4.50, category: 'Paint Tools', visible: false },
  { name: 'Stir Sticks (50-pack)', quantity: 1, unit: 'pack', unitCost: 7.95, category: 'Paint Tools', visible: false },
];

export const getProtectionAndCleanup = () => [
  { name: 'Ram Board Floor Protection (100 sq ft roll)', quantity: 2, unit: 'roll', unitCost: 85.00, category: 'Protection', visible: false },
  { name: '6-mil Plastic Sheeting (10x25 ft)', quantity: 4, unit: 'roll', unitCost: 18.95, category: 'Protection', visible: false },
  { name: '1-mil Plastic Drop Cloth (9x12 ft)', quantity: 6, unit: 'each', unitCost: 3.50, category: 'Protection', visible: false },
  { name: 'Canvas Drop Cloth (9x12 ft)', quantity: 2, unit: 'each', unitCost: 24.95, category: 'Protection', visible: false },
  { name: 'Rosin Paper Roll (3x140 ft)', quantity: 1, unit: 'roll', unitCost: 32.50, category: 'Protection', visible: false },
  { name: 'Carpet Protection Film (24"x200 ft)', quantity: 1, unit: 'roll', unitCost: 45.00, category: 'Protection', visible: false },
  { name: 'Corner Guards (pack of 4)', quantity: 3, unit: 'pack', unitCost: 12.95, category: 'Protection', visible: false },
  { name: 'Doorway Protection Kit', quantity: 3, unit: 'kit', unitCost: 18.50, category: 'Protection', visible: false },
  { name: 'Heavy-Duty Trash Bags (42 gallon, 20-pack)', quantity: 4, unit: 'pack', unitCost: 16.95, category: 'Cleanup', visible: false },
  { name: 'Contractor Trash Bags (55 gallon, 20-pack)', quantity: 3, unit: 'pack', unitCost: 22.50, category: 'Cleanup', visible: false },
  { name: 'Shop Towels (200-count box)', quantity: 2, unit: 'box', unitCost: 28.95, category: 'Cleanup', visible: false },
  { name: 'Microfiber Cleaning Cloths (24-pack)', quantity: 2, unit: 'pack', unitCost: 18.50, category: 'Cleanup', visible: false },
  { name: 'All-Purpose Cleaner (1 gallon)', quantity: 2, unit: 'gallon', unitCost: 12.95, category: 'Cleanup', visible: false },
  { name: 'Degreaser Cleaner (32 oz spray)', quantity: 3, unit: 'bottle', unitCost: 8.95, category: 'Cleanup', visible: false },
  { name: 'Window Cleaner (32 oz spray)', quantity: 2, unit: 'bottle', unitCost: 5.50, category: 'Cleanup', visible: false },
  { name: 'Disinfectant Wipes (2-pack)', quantity: 2, unit: 'pack', unitCost: 11.95, category: 'Cleanup', visible: false },
  { name: 'Broom and Dustpan Set', quantity: 2, unit: 'set', unitCost: 14.95, category: 'Cleanup', visible: false },
  { name: 'Shop Vacuum Filters (3-pack)', quantity: 1, unit: 'pack', unitCost: 16.50, category: 'Cleanup', visible: false },
  { name: 'Vacuum Bags (10-pack)', quantity: 1, unit: 'pack', unitCost: 12.95, category: 'Cleanup', visible: false },
  { name: 'Scrub Brushes (3-pack)', quantity: 1, unit: 'pack', unitCost: 9.95, category: 'Cleanup', visible: false },
  { name: 'Sponges (12-pack)', quantity: 2, unit: 'pack', unitCost: 6.50, category: 'Cleanup', visible: false },
  { name: 'Paper Towels (12-pack)', quantity: 2, unit: 'pack', unitCost: 24.95, category: 'Cleanup', visible: false },
];

export const getSafetyEquipment = () => [
  { name: 'N95 Dust Masks (20-pack)', quantity: 2, unit: 'pack', unitCost: 18.95, category: 'Safety', visible: false },
  { name: 'Safety Glasses (12-pack)', quantity: 1, unit: 'pack', unitCost: 24.50, category: 'Safety', visible: false },
  { name: 'Work Gloves (12 pairs)', quantity: 2, unit: 'pack', unitCost: 22.95, category: 'Safety', visible: false },
  { name: 'Nitrile Gloves (100-count box)', quantity: 2, unit: 'box', unitCost: 16.50, category: 'Safety', visible: false },
  { name: 'Hearing Protection Earplugs (200 pairs)', quantity: 1, unit: 'box', unitCost: 28.95, category: 'Safety', visible: false },
  { name: 'Knee Pads (2 pairs)', quantity: 2, unit: 'pair', unitCost: 18.50, category: 'Safety', visible: false },
  { name: 'First Aid Kit', quantity: 1, unit: 'kit', unitCost: 32.95, category: 'Safety', visible: false },
  { name: 'Fire Extinguisher (5 lb)', quantity: 1, unit: 'each', unitCost: 45.00, category: 'Safety', visible: false },
];

export const getTapes = () => [
  { name: 'Blue Painter\'s Tape 1.5"', quantity: 8, unit: 'roll', unitCost: 6.95, category: 'Tapes', visible: false },
  { name: 'Green Painter\'s Tape 2" (Delicate)', quantity: 4, unit: 'roll', unitCost: 8.50, category: 'Tapes', visible: false },
  { name: 'Duct Tape 2"', quantity: 4, unit: 'roll', unitCost: 5.95, category: 'Tapes', visible: false },
  { name: 'Masking Tape 1"', quantity: 6, unit: 'roll', unitCost: 3.25, category: 'Tapes', visible: false },
  { name: 'Double-Sided Tape', quantity: 3, unit: 'roll', unitCost: 7.50, category: 'Tapes', visible: false },
  { name: 'Gorilla Tape 2"', quantity: 2, unit: 'roll', unitCost: 9.95, category: 'Tapes', visible: false },
  { name: 'Clear Packing Tape', quantity: 4, unit: 'roll', unitCost: 4.50, category: 'Tapes', visible: false },
  { name: 'Electrical Tape (assorted)', quantity: 3, unit: 'roll', unitCost: 3.95, category: 'Tapes', visible: false },
];

export const getMiscConsumables = () => [
  { name: 'Pencils (12-pack)', quantity: 2, unit: 'pack', unitCost: 5.95, category: 'Marking & Layout', visible: false },
  { name: 'Carpenter Pencils (12-pack)', quantity: 1, unit: 'pack', unitCost: 8.50, category: 'Marking & Layout', visible: false },
  { name: 'Permanent Markers (12-pack)', quantity: 1, unit: 'pack', unitCost: 12.95, category: 'Marking & Layout', visible: false },
  { name: 'Chalk Line Refill', quantity: 2, unit: 'bottle', unitCost: 4.25, category: 'Marking & Layout', visible: false },
  { name: 'Lumber Crayons (12-pack)', quantity: 1, unit: 'pack', unitCost: 6.95, category: 'Marking & Layout', visible: false },
  { name: 'Utility Knife Blades (100-pack)', quantity: 1, unit: 'pack', unitCost: 14.95, category: 'Cutting Tools', visible: false },
  { name: 'Reciprocating Saw Blades (assorted 5-pack)', quantity: 2, unit: 'pack', unitCost: 22.50, category: 'Cutting Tools', visible: false },
  { name: 'Circular Saw Blade', quantity: 1, unit: 'each', unitCost: 28.95, category: 'Cutting Tools', visible: false },
  { name: 'Jigsaw Blades (10-pack)', quantity: 1, unit: 'pack', unitCost: 12.95, category: 'Cutting Tools', visible: false },
  { name: 'WD-40 Multi-Use (12 oz)', quantity: 2, unit: 'can', unitCost: 6.95, category: 'Lubricants', visible: false },
  { name: '3-in-1 Oil', quantity: 2, unit: 'bottle', unitCost: 4.50, category: 'Lubricants', visible: false },
  { name: 'Zip Ties (assorted 500-pack)', quantity: 1, unit: 'pack', unitCost: 14.95, category: 'Fastening', visible: false },
  { name: 'Velcro Strips (15 ft roll)', quantity: 2, unit: 'roll', unitCost: 12.50, category: 'Fastening', visible: false },
  { name: 'Shims (Composite, 42-pack)', quantity: 3, unit: 'pack', unitCost: 8.95, category: 'Installation', visible: false },
  { name: 'Wood Filler (1 pint)', quantity: 2, unit: 'pint', unitCost: 9.50, category: 'Fillers', visible: false },
  { name: 'Spackling Paste (1 quart)', quantity: 2, unit: 'quart', unitCost: 7.95, category: 'Fillers', visible: false },
  { name: 'Drywall Joint Compound (1 gallon)', quantity: 1, unit: 'gallon', unitCost: 12.50, category: 'Fillers', visible: false },
];
