import { ArrowRight, BookOpenCheck, CheckCircle2, Compass, Sparkles } from "lucide-react";

export type PortalGuideKey = "customer" | "vendor" | "subcontractor" | "employee" | "advertiser" | "investor" | "property_manager" | "condo_manager" | "landlord" | "territory" | "condo_association" | "admin";

type Guide = { title: string; summary: string; start: string; sections: { name: string; detail: string; status: string }[] };

const GUIDES: Record<PortalGuideKey, Guide> = {
  customer: { title: "Your customer portal, explained", summary: "Manage requests, quotes, contracts, payments, plans, rewards, and conversations with Black Phoenix in one place.", start: "Start with Projects to review active work, then use Quotes & Invoices to approve work and Payments to settle balances.", sections: [{ name: "Projects & requests", detail: "Track active work, request service, and review project updates.", status: "Project delivery" }, { name: "Quotes, contracts & payments", detail: "Review proposals, sign contracts, and complete secure invoice payments.", status: "Commercial records" }, { name: "Plans & add-ons", detail: "Review maintenance hours, usage, invoices, plan options, and requested additions.", status: "Plan management" }, { name: "Messages, referrals & shop", detail: "Talk with your team, share referrals, browse offers, and place store orders.", status: "Account benefits" }] },
  vendor: { title: "Your vendor operations portal", summary: "Use this workspace to manage orders, products, promotions, invoices, payments, integrations, and account plan features.", start: "Begin with Orders for fulfillment activity and Products to keep your catalog current.", sections: [{ name: "Orders & products", detail: "Track orders and maintain your product catalog.", status: "Commerce operations" }, { name: "Promotions & performance", detail: "Manage promotion activity and review performance.", status: "Growth tools" }, { name: "Invoices, payments & plans", detail: "See financial activity and your plan features in one place.", status: "Account billing" }, { name: "API settings & messages", detail: "Manage approved integrations and communicate with the Black Phoenix team.", status: "Connected operations" }] },
  subcontractor: { title: "Your subcontractor work hub", summary: "Review jobs, submit secure bids with files, track payment records, plan benefits, performance, and messages.", start: "Open Dashboard to find available bid opportunities, then use My Bids to follow each submission.", sections: [{ name: "Job opportunities", detail: "Review work scope, timing, budget ranges, and requirements.", status: "Work pipeline" }, { name: "Secure bids", detail: "Submit pricing, notes, duration, and private image/video attachments.", status: "Bid workflow" }, { name: "Payments & performance", detail: "Monitor payment records, work performance, and plan activity.", status: "Business health" }, { name: "Messages", detail: "Keep project communication in the portal.", status: "Collaboration" }] },
  employee: { title: "Your employee workspace", summary: "Access schedules, assigned tasks, time records, documents, performance, plan information, and support messages.", start: "Check Schedule first, then use Tasks and Timesheet throughout the workday.", sections: [{ name: "Schedule & tasks", detail: "See upcoming work and assigned responsibilities.", status: "Daily operations" }, { name: "Timesheet", detail: "Review and submit tracked work hours.", status: "Work hours" }, { name: "Documents & messages", detail: "Find shared documents and communicate with support.", status: "Team resources" }, { name: "Plans, performance & referrals", detail: "Review eligible account benefits and performance tools.", status: "Benefits" }] },
  advertiser: { title: "Your advertiser command space", summary: "Manage campaigns, placements, media, previews, billing, analytics, plan benefits, and communications.", start: "Use Campaigns for active promotion work and Analytics to measure results.", sections: [{ name: "Campaigns & placements", detail: "Manage live advertising activity and available placements.", status: "Campaign delivery" }, { name: "Media & live previews", detail: "Review creative assets and how ads are presented.", status: "Creative control" }, { name: "Analytics & billing", detail: "Monitor results and account financial activity.", status: "Performance reporting" }, { name: "Plans, referrals & messages", detail: "Understand included features and stay connected with the team.", status: "Account growth" }] },
  investor: { title: "Your investor portal guide", summary: "Review your portfolio, opportunities, reports, distributions, documents, plan information, and communications.", start: "Begin with Portfolio, then review Opportunities and Documents before making a decision.", sections: [{ name: "Portfolio & reports", detail: "Follow portfolio activity and available reporting.", status: "Investment visibility" }, { name: "Opportunities", detail: "Explore active offerings and their supporting details.", status: "Decision support" }, { name: "Distributions & documents", detail: "Review distribution information and important records.", status: "Investor records" }, { name: "Plans & messages", detail: "Access plan benefits and communicate securely.", status: "Account support" }] },
  property_manager: { title: "Your property management hub", summary: "Manage properties, work requests, CRM contacts, financial activity, maintenance plans, and operational communication.", start: "Review Work Requests first, then use Properties and CRM to keep the account organized.", sections: [{ name: "Properties & work requests", detail: "Track your portfolio and approve or reject assigned work.", status: "Property operations" }, { name: "CRM", detail: "Maintain tenants, owners, vendors, prospects, and interaction history.", status: "Relationship management" }, { name: "Plans & financials", detail: "Monitor maintenance plan use, invoices, payments, and property revenue tools.", status: "Account control" }, { name: "Messages & settings", detail: "Keep decisions and account preferences in one place.", status: "Collaboration" }] },
  condo_manager: { title: "Your condo management hub", summary: "Manage units, owners, work requests, CRM, financials, maintenance plans, and association communication.", start: "Use Work Requests for approvals, then keep units and owners current.", sections: [{ name: "Units, owners & requests", detail: "Manage the association roster and assigned maintenance decisions.", status: "Association operations" }, { name: "CRM", detail: "Track owner, tenant, vendor, and prospect relationships.", status: "Relationship management" }, { name: "Plans & financials", detail: "Review plan usage, financial activity, and revenue tools.", status: "Financial visibility" }, { name: "Messages & settings", detail: "Coordinate decisions and maintain account settings.", status: "Collaboration" }] },
  landlord: { title: "Your landlord portal guide", summary: "Keep properties, tenants, maintenance decisions, CRM records, plan usage, and financial activity together.", start: "Start with Maintenance to act on requests, then keep Properties and Tenants updated.", sections: [{ name: "Properties & tenants", detail: "Maintain your portfolio and tenant roster.", status: "Portfolio management" }, { name: "Maintenance", detail: "Review, approve, or reject work requests assigned to you.", status: "Maintenance workflow" }, { name: "CRM & financials", detail: "Track relationships, payments, invoices, and plan information.", status: "Account records" }, { name: "Messages & settings", detail: "Coordinate with Black Phoenix and manage preferences.", status: "Collaboration" }] },
  territory: { title: "Your territory owner portal", summary: "Manage customer and subcontractor activity, work pipeline, subscriptions, CRM, analytics, referrals, and territory operations.", start: "Review Pipeline for work activity, then use Customers and Subcontractors to manage your network.", sections: [{ name: "Pipeline & analytics", detail: "Track request movement and territory performance.", status: "Territory operations" }, { name: "Customers & subcontractors", detail: "Manage the people and partners in your territory.", status: "Network management" }, { name: "Subscriptions & plans", detail: "Review account plan activity and member benefits.", status: "Recurring services" }, { name: "CRM, deals & referrals", detail: "Grow relationships and track referrals.", status: "Growth tools" }] },
  condo_association: { title: "Your condo association portal", summary: "Review maintenance, approvals, financials, units, vendors, documents, team access, and referral tools.", start: "Start with Maintenance and Approvals, then use Units and Documents to keep the association organized.", sections: [{ name: "Maintenance & approvals", detail: "Submit and review association work requests.", status: "Association care" }, { name: "Financials & vendors", detail: "Review financial details and vendor activity.", status: "Operations control" }, { name: "Units, documents & team", detail: "Maintain association records and collaboration resources.", status: "Association records" }, { name: "Deals & referrals", detail: "Access member opportunities and referral benefits.", status: "Member benefits" }] },
  admin: { title: "Your operations portal guide", summary: "Dispatch work, review plan records, monitor alerts, and support customers and employees from one operational view.", start: "Begin with Dispatch for active operations, then use Alerts to handle issues requiring attention.", sections: [{ name: "Dispatch", detail: "Coordinate operational work and assignments.", status: "Live operations" }, { name: "Plans", detail: "Review subscription and maintenance plan records.", status: "Plan oversight" }, { name: "Alerts", detail: "Respond to system and workflow notifications.", status: "Command Center support" }, { name: "Customer & employee support", detail: "Handle account questions and internal assistance.", status: "Service quality" }] },
};

export default function PortalFeatureGuide({ portal }: { portal: PortalGuideKey }) {
  const guide = GUIDES[portal];
  return <section className="mx-auto max-w-6xl space-y-6">
    <div className="overflow-hidden rounded-2xl border border-orange-500/20 bg-gradient-to-br from-orange-500/10 via-[#17120e] to-[#111111] p-6 md:p-8">
      <div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-orange-300"><BookOpenCheck className="h-4 w-4" /> Portal guide</p><h2 className="mt-3 text-2xl font-semibold text-white md:text-3xl">{guide.title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-gray-300">{guide.summary}</p></div><div className="max-w-sm border border-white/10 bg-black/20 p-4"><p className="flex items-center gap-2 text-sm font-semibold text-white"><Compass className="h-4 w-4 text-orange-300" /> Where to start</p><p className="mt-2 text-sm leading-6 text-gray-400">{guide.start}</p></div></div>
    </div>
    <div className="grid gap-4 md:grid-cols-2">{guide.sections.map((section, index) => <article key={section.name} className="border border-white/10 bg-[#151515] p-5 transition hover:border-orange-400/30"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-orange-500/10 text-xs font-bold text-orange-300">0{index + 1}</span><div><h3 className="font-semibold text-white">{section.name}</h3><p className="mt-2 text-sm leading-6 text-gray-400">{section.detail}</p></div></div><CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-400/80" /></div><p className="mt-4 flex items-center gap-1 text-xs font-semibold uppercase tracking-[0.13em] text-orange-200"><Sparkles className="h-3.5 w-3.5" /> {section.status} <ArrowRight className="h-3.5 w-3.5" /></p></article>)}</div>
  </section>;
}
